export const productsTypes = {
  GET_INITIAL_PRODUCTS: "GET_INITIAL_PRODUCTS",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_RANDOM_PRODUCTS: "GET_RANDOM_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  SEARCH_WITH_FIELD_PRODUCTS: "SEARCH_WITH_FIELD_PRODUCTS",
  GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
};
