export const userTypes = {
  LOADING: "LOADING",
  ERROR_MSG: "ERROR_MSG",
  CLEAR_ERROR_MSG: "CLEAR_ERROR_MSG",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
